
const PRODUCTS=[{"id": 2, "name": "Creed Aventus", "prices": {"6 ml": 150, "10 ml": 250, "20 ml": 450, "30 ml": 600, "50 ml": "Call/SMS for price"}, "tags": "Fresh \u2022 Fruity \u2022 Powerful", "images": ["assets/product-2-1.jpg", "assets/product-2-2.jpg", "assets/product-2-3.jpg"]}, {"id": 4, "name": "Versace Eros", "prices": {"6 ml": 150, "10 ml": 250, "20 ml": 450, "30 ml": 600, "50 ml": "Call/SMS for price"}, "tags": "Fresh \u2022 Citrus \u2022 Seductive", "images": ["assets/product-4-1.jpg", "assets/product-4-2.jpg", "assets/product-4-3.jpg"]}, {"id": 10, "name": "Dior Sauvage", "prices": {"6 ml": 140, "10 ml": 230, "20 ml": 420, "30 ml": 550, "50 ml": "Call/SMS for price"}, "tags": "Fresh \u2022 Spicy \u2022 Iconic", "images": ["assets/product-10-1.jpg", "assets/product-10-2.jpg", "assets/product-10-3.jpg"]}];
const SOCIAL={facebook:'https://www.facebook.com/opensecret311',instagram:'#',tiktok:'https://www.tiktok.com/@opensecret311',youtube:'https://www.youtube.com/@OpenSecret311',whatsapp:'https://api.whatsapp.com/send?phone=8801581906311'};
let cart=JSON.parse(localStorage.getItem('openSecretCart')||'[]');
let deliveryLocation=null;const DELIVERY_FEE={inside:70,outside:120};
function setLocation(loc){deliveryLocation=loc;document.getElementById('locInside').classList.toggle('active',loc==='inside');document.getElementById('locOutside').classList.toggle('active',loc==='outside');renderCart()}
const money=n=>'৳ '+Number(n).toLocaleString('en-BD');
function save(){localStorage.setItem('openSecretCart',JSON.stringify(cart));renderCart();}
function addToCart(id,size='6 ml'){const p=PRODUCTS.find(x=>x.id===id);const price=p.prices[size];const key=id+'-'+size;const found=cart.find(x=>x.key===key);if(found)found.qty++;else cart.push({key,id,size,price,qty:1});save();openCart();}
function changeQty(key,delta){const x=cart.find(i=>i.key===key);if(!x)return;x.qty+=delta;if(x.qty<=0)cart=cart.filter(i=>i.key!==key);save();}
function removeItem(key){cart=cart.filter(i=>i.key!==key);save();}
function renderCart(){const box=document.getElementById('cartItems');if(!box)return;document.getElementById('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);document.getElementById('cartTitle').textContent=cart.reduce((a,x)=>a+x.qty,0);const orderBtn=document.getElementById('orderBtn');const feeEl=document.getElementById('deliveryFee');const fee=deliveryLocation?DELIVERY_FEE[deliveryLocation]:0;if(!cart.length){box.innerHTML='<div class="empty">Your cart is empty.<br><br><a class="btn" href="#shop" onclick="closeCart()">Shop fragrances</a></div>';document.getElementById('subtotal').textContent='৳ 0';feeEl.textContent=deliveryLocation?money(fee):'Select location';document.getElementById('total').textContent=deliveryLocation?money(fee):'৳ 0';orderBtn.disabled=true;orderBtn.textContent='Cart is empty';return}let subtotal=0;box.innerHTML=cart.map(x=>{const p=PRODUCTS.find(p=>p.id===x.id);const line=typeof x.price==='number'?x.price*x.qty:0;subtotal+=line;return `<div class="cart-item"><img src="${p.images[0]}" alt="${p.name}"><div><h4>${p.name}</h4><small>${x.size} · ${typeof x.price==='number'?money(x.price):'Price on request'}</small><div class="qty"><button onclick="changeQty('${x.key}',-1)">−</button><b>${x.qty}</b><button onclick="changeQty('${x.key}',1)">+</button></div></div><button class="remove" onclick="removeItem('${x.key}')">⌫</button></div>`}).join('');document.getElementById('subtotal').textContent=money(subtotal);if(deliveryLocation){feeEl.textContent=money(fee);document.getElementById('total').textContent=money(subtotal+fee);orderBtn.disabled=false;orderBtn.textContent='Order on WhatsApp'}else{feeEl.textContent='Select location';document.getElementById('total').textContent=money(subtotal);orderBtn.disabled=true;orderBtn.textContent='Select delivery location first'}}
function openCart(){document.getElementById('cart').classList.add('open');document.getElementById('overlay').classList.add('open');renderCart()}
function closeCart(){document.getElementById('cart').classList.remove('open');document.getElementById('overlay').classList.remove('open')}
function orderCartWhatsApp(){if(!cart.length){alert('Your cart is empty.');return}if(!deliveryLocation){alert('Please select your delivery location first.');return}const fee=DELIVERY_FEE[deliveryLocation];const locLabel=deliveryLocation==='inside'?'Inside Dhaka':'Outside Dhaka';let subtotal=0;let lines=cart.map((x,i)=>{const p=PRODUCTS.find(p=>p.id===x.id);const line=typeof x.price==='number'?x.price*x.qty:0;subtotal+=line;return `${i+1}. ${p.name} — ${x.size} — Qty: ${x.qty} — ${typeof x.price==='number'?money(line):'Price on request'}`});const msg=`Hi OPEN SECRET, I want to place an order:%0A%0A${encodeURIComponent(lines.join('\n'))}%0A%0ASubtotal: ${encodeURIComponent(money(subtotal))}%0ADelivery Location: ${encodeURIComponent(locLabel)}%0ADelivery: ${encodeURIComponent(money(fee))}%0ATotal: ${encodeURIComponent(money(subtotal+fee))}%0A%0APlease confirm my order.`;window.location.href='https://api.whatsapp.com/send?phone=8801581906311&text='+msg}
function setupSocial(){document.querySelectorAll('[data-social]').forEach(a=>{const k=a.dataset.social;if(SOCIAL[k]&&SOCIAL[k]!=='#')a.href=SOCIAL[k];else if(k==='whatsapp')a.href=SOCIAL.whatsapp;a.target='_blank'})}
function renderProducts(){const el=document.getElementById('products');el.innerHTML=PRODUCTS.map(p=>{
  if(p.comingSoon){
    return `<article class="card coming-soon"><div class="card-img"><img src="${p.images[0]}" alt="${p.name}"><div class="soon-badge">Coming Soon</div></div><div class="card-body"><h3>${p.name}</h3><div class="tags">${p.tags}</div><div class="card-row"><div><span class="from">Launching Soon</span></div></div></div></article>`;
  }
  return `<article class="card"><a href="product.html?id=${p.id}"><div class="card-img"><img src="${p.images[0]}" alt="${p.name}"></div></a><div class="card-body"><h3>${p.name}</h3><div class="tags">${p.tags}</div><div class="card-row"><div><span class="from">From </span><span class="price">${money(p.prices['6 ml'])}</span></div><button class="add" title="Add to cart" onclick="event.stopPropagation();addToCart(${p.id},'6 ml')">+</button></div></div></article>`;
}).join('')}
renderProducts();renderCart();setupSocial();
